### ISSUE TITLE
cfas should use python2 in line 1

### ISSUE THREAD

**Issue by OleHolmNielsen** [runefriborg/cfas#7]
Hi Rune,

We still like to use your cfas tool!  But since Python2 is now superceded by Python3, it would be great if you explicitly use python2 in line 1 of the script:
#!/usr/bin/env python
should be replaced by
#!/usr/bin/env python2

Are there any chances that you will rewrite cfas for Python3?

Thanks,
Ole

**Comment by runefriborg** [comment]
Hi Ole,

Good to know, that there are users out there. I will take a look at updating the code soon.

Rune

**Comment by runefriborg** [comment]
I wanted to make it python3 compatible, but I didn't find the time. So for now I just made the change you suggested.

**Comment by OleHolmNielsen** [comment]
Thanks a lot, Rune!
